Determine iam endpoint based on token exchange URL in VPC config for …
IBM/secret-utils-lib pull request #27
Opened 2024-01-18 03:24 UTC by GunaKKIBM

…VPC gen2 clusters

2024-01-22 09:25 UTC, ambiknai requested changes
Changes lgtm. Please add UT.

2024-01-22 09:29 UTC, sameshai approved these changes
LGTM

2024-01-22 11:28 UTC, ambiknai approved these changes

2024-01-22 11:30 UTC, prankulmahajan approved these changes
lgtm

2024-01-23 05:24 UTC, GunaKKIBM commented on pkg/config/cluster_config.go
> +			return config.VPC.G2TokenExchangeURL + tokenExchangePath, providedTokenExchangeURL, nil
isURLFramed

2024-01-23 05:26 UTC, GunaKKIBM commented on pkg/config/cluster_config.go
> +			return config.VPC.G2TokenExchangeURL + tokenExchangePath, providedTokenExchangeURL, nil
Change the naming convention - to make it clear it is. boolean variable

2024-01-23 05:30 UTC, GunaKKIBM commented on pkg/config/config_test.go
> +			expectedTokenURL:         utils.ProdPrivateIAMURL + tokenExchangePath,
Hard code the return expected value

2024-01-23 05:31 UTC, GunaKKIBM commented on pkg/config/config_test.go
> +			providedTokenExchangeURL: false,
Change this variable name

2024-01-23 05:43 UTC, GunaKKIBM commented on pkg/config/config_test.go
> +		},
Add couple of more negative test cases

2024-01-23 10:02 UTC, arahamad approved these changes
lgtm

2024-01-23 10:27 UTC, merged