Satellite support for token exchange URL
IBM/secret-utils-lib pull request #5
Opened 2022-05-13 04:15 UTC by GunaKKIBM

2022-05-13 14:17 UTC, skorati approved these changes
looks good.
Please open a GHE on issues we discussed and we can track there.

2022-05-14 05:14 UTC, arahamad requested changes
can you fix these comments

2022-05-14 05:14 UTC, arahamad commented on pkg/k8s_utils/secret.go
> +		kc.logger.Error("Error fetching cluster-info configmap", zap.Error(err))
can we make error msg generic as this is not a cluster-info cm , its secret which is passed to this method

2022-05-14 05:14 UTC, arahamad commented on pkg/k8s_utils/secret.go
> +		kc.logger.Error("cluster-config.json is not present")
same here to make error msg generic.

2022-05-14 17:31 UTC, arahamad approved these changes
lgtm

2022-05-14 17:31 UTC, merged